name: Get previous job's status

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
          - dev
          - uat

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Print 'Build' step
        run: echo "Build step passed."

  deploy:
    needs: [build]
    uses: ./.github/workflows/reusabe-deploy.yml
    with:
      environment: ${{ inputs.environment }}

  notify:
   needs: [deploy]
   runs-on: ubuntu-latest
   if: always() && inputs.environment == 'prod' && needs.deploy.result != 'skipped'
   steps:
      - name: Print the 'deploy' job status
        run: echo "deploy job's status- ${{ needs.deploy.outputs.job_status }}"
