name: Get previous job's status

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: 'prod'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      job_status: ${{ job.status }}
    steps:
      - name: Print 'Build' step
        run: echo "Build step passed."

  deploy:
    needs: [build]
    runs-on: ubuntu-latest 
    outputs:
      job_status: ${{ job.status }}
    steps:
      - name: Print deploy step
        run: echo "Deploy step"

      - name: Fail the step
        run: exit 1

  notify:
   needs: [deploy]
   runs-on: ubuntu-latest
   if: always() && inputs.environment == 'prod' && needs.deploy.result != 'skipped'
   steps:
      - name: Print the 'build' job status
        run: echo "build job's status- ${{ needs.deploy.outputs.job_status }}"
