name: Reusable Deploy workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    outputs:
      job_status:
        description: "The status of the job"
        value: ${{ jobs.deploy.status }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      job_status: ${{ job.status }}
    steps:
      - name: Print deploy step
        run: echo "Deploy step"    
