name: Reusable Deploy workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    outputs:
      job_status:
        description: "The status of the job"
        value: ${{ jobs.deploy.outcome }}

jobs:
  deploy:
    runs-on: ubuntu-latest  
    steps:
      - name: Print deploy step
        run: echo "Deploy step"    
